### ISSUE TITLE
non-zero starting nonce

### ISSUE THREAD

**Issue by meowsbits** [eth-classic/kensington#7]
https://github.com/eth-classic/kensington/blob/master/gethc.json#L5
https://github.com/eth-classic/kensington/blob/master/parity.json#L22

This makes it impossible for multi-geth to participate, since neither go-ethereum nor multi-geth support this feature since 2016. https://github.com/ethereum/go-ethereum/commit/aad4890082c1624795991d534db9497c8b63630d

**Comment by soc1c** [comment]
so, how is multi geth dealing with morden? it uses the same starting nonce

**Comment by meowsbits** [comment]
multi-geth doesn't support morden, either

**Comment by soc1c** [comment]
I'm a big fan of removing features lol
